name: Version Bump and Create PR

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "Select the version type to bump:"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and update to the latest main
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Switch to Bump Branch
        run: |
          git checkout -b version-bump-${{ github.run_id }}

      - name: Bump Version
        run: |
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          IFS='.' read -ra ADDR <<< "$current_version"
          if [ "${{ github.event.inputs.versionType }}" == "major" ]; then
            let ADDR[0]+=1
            ADDR[1]=0
            ADDR[2]=0
          elif [ "${{ github.event.inputs.versionType }}" == "minor" ]; then
            let ADDR[1]+=1
            ADDR[2]=0
          elif [ "${{ github.event.inputs.versionType }}" == "patch" ]; then
            let ADDR[2]+=1
          fi
          new_version="${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
          echo $new_version > VERSION
          echo "New version: $new_version"
          cat VERSION

      - name: Commit and Push Changes
        run: |
          git add VERSION
          git commit -m "Bump version: $current_version → $new_version"
          git push --set-upstream origin version-bump-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update version to $new_version"
          title: "Release v$new_version"
          body: |
            ## Automated Release
            This PR is auto-generated by the CI to bump the version to $new_version.
            Please review the changes and merge if appropriate.
          labels: release
          branch: version-bump-${{ github.run_id }}
          base: main
          signoff: true
          delete-branch: true
