name: Version Bump and Create PR

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "Select the version type to bump:"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and update to the latest main
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install bump2version
        run: pip install bump2version

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Switch to Bump Branch
        run: |
          git checkout -b version-bump-${{ github.run_id }}

      - name: Bump Version
        run: |
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV
          bump2version --current-version "$current_version" ${{ github.event.inputs.versionType }} VERSION --commit --verbose
          git status
          new_version=$(cat VERSION)
          echo "New version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Push Changes to Bump Branch
        run: |
          git push --set-upstream origin version-bump-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update version to ${{ env.NEW_VERSION }}"
          title: "Release v${{ env.NEW_VERSION }}"
          body: "This PR is auto-generated by the CI to bump the version to ${{ env.NEW_VERSION }}. Please review the changes and merge if appropriate."
          branch: version-bump-${{ github.run_id }}
          base: main
