name: Version Management

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "Select the version type to bump:"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install bump2version
        run: pip install bump2version

      - name: Create Version Bump Branch
        run: |
          git fetch --all
          git checkout main
          git pull
          git checkout -b version-bump-${{ github.run_id }}

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version and Create Git Tag
        id: bump-version
        run: |
          current_version=$(grep 'version=' setup.py | sed -n 's/.*version="\(.*\)"/\1/p')
          bump2version ${{ github.event.inputs.versionType }} --config-file .bumpversion.cfg
          new_version=$(grep 'version=' setup.py | sed -n 's/.*version="\(.*\)"/\1/p')
          echo "::set-output name=new_version::$new_version"
          git add .
          git commit -m "Bump version from $current_version to $new_version"

      - name: Show changes
        run: |
          git status
          git diff

      - name: Push Changes
        run: |
          git push --set-upstream origin version-bump-${{ github.run_id }}

      - name: Push Tags
        run: |
          git push origin --tags

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update version to ${{ steps.bump-version.outputs.new_version }}"
          title: "Release v${{ steps.bump-version.outputs.new_version }} [${{ github.event.inputs.versionType }}]"
          body: "This PR is auto-generated by the CI to bump the version to ${{ steps.bump-version.outputs.new_version }}. Please review the changes and merge if appropriate."
          branch: version-bump-${{ github.run_id }}
          base: main
