name: Version Bump and Create PR

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: "Select the version type to bump:"
        required: true
        default: "patch"
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and update to the latest main
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install bump2version
        run: pip install bump2version

      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Switch to Bump Branch
        run: |
          git checkout -b version-bump-${{ github.run_id }}

      - name: Bump Version
        run: |
          echo "current_version=$(cat VERSION)" >> $GITHUB_ENV
          echo "Current version: $current_version"
          bump2version --current-version "$current_version" "${{ github.event.inputs.versionType }}" VERSION --commit --allow-dirty --verbose
          echo "new_version=$(cat VERSION)" >> $GITHUB_ENV
          echo "New version: $new_version"

      - name: Push Changes to Bump Branch
        run: |
          git status
          git push --set-upstream origin version-bump-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version to $new_version"
          title: "Release v$new_version"
          body: "This PR is auto-generated by the CI to bump the version to $new_version. Please review the changes and merge if appropriate."
          branch: version-bump-${{ github.run_id }}
          base: main
